### ISSUE TITLE
CUE 4 Visualizar Historial Académico

### ISSUE THREAD

**Issue by DannyOrt** [JavierMung/SAES#2]
Errores Ortográficos:
- KARDEX = **KÁRDEX**
- Compuatcionales = **Computacionales.**

![image](https://user-images.githubusercontent.com/28195821/168527912-d0dd2e13-47e8-47b0-97c3-3128bf7fdce4.png)

**DAVID REYES CASTRO**

**Comment by EliezerRoblesDiaz** [comment]
<img width="530" alt="Captura de Pantalla 2022-05-16 a la(s) 1 06 13" src="https://user-images.githubusercontent.com/84756678/168529391-d1b3f050-3df0-4b5f-9df4-e75fb0fc14a8.png">

**Comment by DannyOrt** [comment]
@EliezerRoblesDiaz 
Barra de Menú Lateral Izquierda - Alumno

Error Ortográfico:
Kardex = KÁRDEX

![image](https://user-images.githubusercontent.com/28195821/168529914-9f6e9ba4-5b7a-49d0-9f1a-38784ec6504f.png)

CUE 4 Visualizar Historial Académico

Error de Sintaxis:
Promedio global = **Promedio Global**
![image](https://user-images.githubusercontent.com/28195821/168530183-93b29adb-7e99-48eb-bb9a-2b72843f26ff.png)
