### ISSUE TITLE
Barra de Menú Lateral Izquierda - Alumno

### ISSUE THREAD

**Issue by DannyOrt** [JavierMung/SAES#3]
Errores Ortográficos y de Sintaxis:

- **cambiar contraseña = **Cambiar Contraseña.****
- Periodo actual = **Periodo Actual.**
- Historial academico =**Historial Académico.**
- Datos generales = **Datos Generales.**
- Saberes adquiridos = **Saberes Adquiridos.**

![image](https://user-images.githubusercontent.com/28195821/168528798-c17a4482-4c35-44a8-b3a9-31a78d72aa2b.png)

**DAVID REYES CASTRO**

**Comment by EliezerRoblesDiaz** [comment]
<img width="530" alt="Captura de Pantalla 2022-05-16 a la(s) 1 11 20" src="https://user-images.githubusercontent.com/84756678/168529927-8aeec481-8b90-4fa3-af2f-8802abe7a520.png">

**Comment by EliezerRoblesDiaz** [comment]
<img width="538" alt="Captura de Pantalla 2022-05-16 a la(s) 1 11 54" src="https://user-images.githubusercontent.com/84756678/168529984-038ddba0-6f20-44fb-80b4-259b4afdae90.png">
