### ISSUE TITLE
CUE 5.2 Modificar Datos Médicos

### ISSUE THREAD

**Issue by DannyOrt** [JavierMung/SAES#4]
Errores Ortográficos y de Sintaxis:

- Datos medicos = **Datos Médicos.**
- Institución medica = **Institución Médica.**
- Tipos de sangre = **Tipo de Sangre.**
- Numero de seguro social = **Número de Seguro Social.**
- Problemas físicos = **Problemas Físicos.**

![image](https://user-images.githubusercontent.com/28195821/168529629-e7681efb-ac20-4ced-a395-3c387bc9f1ab.png)

**DAVID REYES CASTRO**

**Comment by EliezerRoblesDiaz** [comment]
<img width="509" alt="Captura de Pantalla 2022-05-16 a la(s) 1 15 31" src="https://user-images.githubusercontent.com/84756678/168530463-eb2c788b-d024-46a8-9aaf-0e8cfc1038ee.png">

**Comment by DannyOrt** [comment]
@EliezerRoblesDiaz 
Errores Ortográficos:

- Tipos de Sangre = **Tipo** de Sangre.
- Numero de Seguro Social = **Número** de Seguro Social

![image](https://user-images.githubusercontent.com/28195821/168530964-33750300-05cf-4e5e-8169-ab452cdbca0d.png)

**Comment by DannyOrt** [comment]
@EliezerRoblesDiaz 

Errores de Sintaxis: 

- Datos Médicos = **DATOS MÉDICOS**  (Todas las secciones están en Mayúscula)

**Comment by EliezerRoblesDiaz** [comment]
<img width="530" alt="Captura de Pantalla 2022-05-16 a la(s) 1 21 42" src="https://user-images.githubusercontent.com/84756678/168531273-6abbcdd1-9cef-4807-9070-80fe252fdf7a.png">
<img width="533" alt="Captura de Pantalla 2022-05-16 a la(s) 1 23 21" src="https://user-images.githubusercontent.com/84756678/168531481-38665b33-cd7e-46f6-a495-a9c07aed61a8.png">

 Listo @DannyOrt!
