### ISSUE TITLE
CUE 9.2 Cambiar Contraseña

### ISSUE THREAD

**Issue by DannyOrt** [JavierMung/SAES#5]
Errores de Sintaxis: 

- Contraseña actual = **Contraseña Actual**
- Contraseña nueva = **Contraseña Nueva**

![image](https://user-images.githubusercontent.com/28195821/168531709-fa2cd484-88d7-41c8-85a7-d62b59d3d64b.png)

**DAVID REYES CASTRO**

**Comment by EliezerRoblesDiaz** [comment]
<img width="515" alt="Captura de Pantalla 2022-05-16 a la(s) 11 39 49" src="https://user-images.githubusercontent.com/84756678/168641779-b87ade16-9ae8-404f-91a2-849d6ebe0dac.png">
