### ISSUE TITLE
IUE 1

### ISSUE THREAD

**Issue by AMonterM** [JavierMung/SAES#6]
-Acento botón INICIAR SESIÓN.
-Ingresando una letra en campo Usuario complementar el mensaje "Usuario Inválido, NO cumple con el formato correcto".
-*mensajes para contraseña cuando no es correcta y si el usuario no esta registrado.

**Comment by EliezerRoblesDiaz** [comment]
Solo se ha implementado el 1. -Acento botón INICIAR SESIÓN.
