### ISSUE TITLE
IUE 8.1 Visualizar calificaciones de exámenes de saberes previos

### ISSUE THREAD

**Issue by AMonterM** [JavierMung/SAES#7]
Acento examenes=Exámenes  en el título de la tabla y en la columna Calificacion=Calificación

**Comment by EliezerRoblesDiaz** [comment]
<img width="528" alt="Captura de Pantalla 2022-05-23 a la(s) 16 01 48" src="https://user-images.githubusercontent.com/84756678/169905518-50314363-c517-4017-9a04-e7f8de87baa9.png">
